use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use uuid::Uuid;

use crate::turn_runtime::TurnRuntimeState;

/// A single node in the conversation tree.
///
/// Every user/AI exchange is a turn. Turns form a tree via `parent_turn_id`:
/// - `parent_turn_id IS NULL` marks the root turn (one per session).
/// - Multiple turns sharing the same `parent_turn_id` represent forks.
/// - Each root-to-leaf path is an independent LLM conversation context.
///
/// A turn may involve multiple function-call round trips with the LLM before
/// reaching a final response; all intermediate messages are captured in
/// `turn_messages`.
#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct Turn {
    /// Unique identifier for this turn node.
    pub id: Uuid,

    /// The session (conversation tree) this turn belongs to.
    pub session_id: Uuid,

    /// Self-referencing FK forming the adjacency list.
    /// `NULL` for the root turn; otherwise points to the parent turn node.
    /// `ON DELETE SET NULL` -- if the parent is deleted, children become
    /// orphans rather than being cascade-deleted, preserving history.
    pub parent_turn_id: Option<Uuid>,

    /// Points FROM the original (old/superseded) turn TO the new retry turn.
    /// Only set on the *original* turn after a retry. The retry itself is a
    /// new sibling node (same parent) -- retries are siblings, not children,
    /// because they *replace* rather than extend the original turn.
    /// `ON DELETE SET NULL` on both sides to avoid cascading deletion.
    pub retry_turn_id: Option<Uuid>,

    /// Lifecycle status of this turn.
    /// One of: `"running"`, `"awaiting_approval"`, `"completed"`, `"failed"`.
    /// Uses a CHECK constraint (not a PostgreSQL ENUM) so adding new statuses
    /// only requires an application-level change, not a database migration.
    pub status: String,

    /// The raw text the user typed to initiate this turn.
    /// `None` for turns created programmatically (e.g. retries where the user
    /// text is inherited from the original turn).
    pub user_text: Option<String>,

    /// The final text response from the AI assistant.
    /// `None` while the turn is still `running` or `awaiting_approval`.
    /// For turns that produce only tool calls with no text, this may remain
    /// `None` even after completion.
    pub assistant_text: Option<String>,

    /// Protocol-native message transcript for this turn.
    ///
    /// A JSONB array where each entry is a `{ role, content }` object whose
    /// inner structure matches the session's protocol:
    /// - **OpenAI**: `InputItem` / `OutputItem` format from the Responses API.
    /// - **Anthropic**: Content block format from the Messages API.
    ///
    /// Stored as JSONB (not a separate messages table) for several reasons:
    /// 1. Avoids complex joins for every conversation reconstruction.
    /// 2. Enables lossless round-tripping of protocol-specific fields.
    /// 3. The DB is opaque to the structure; the application owns
    ///    serialization/deserialization.
    /// 4. Each turn's transcript is self-contained -- no cross-turn message
    ///    sharing is needed.
    pub turn_messages: JsonValue,

    /// OpenAI Responses API `response.id` for conversation continuity.
    ///
    /// Only populated for sessions using the OpenAI protocol. The Responses
    /// API allows referencing a previous response ID to continue the
    /// conversation server-side. Without storing this, follow-up requests
    /// would have to resend the full conversation history every time.
    pub response_id: Option<String>,

    /// The LLM provider that handled this turn (e.g. `"openai"`, `"anthropic"`).
    pub provider: Option<String>,

    /// The specific model used (e.g. `"gpt-4o"`, `"claude-sonnet-4-20250514"`).
    pub model: Option<String>,

    /// Number of input (prompt) tokens consumed by this turn.
    pub input_tokens: Option<i32>,

    /// Number of output (completion) tokens generated by this turn.
    pub output_tokens: Option<i32>,

    /// Number of tokens served from the provider's prompt cache (reduces cost).
    pub cached_tokens: Option<i32>,

    /// Structured error information when `status` is `"failed"`.
    /// Contains a JSON object like `{ "kind": "abandoned", "message": "..." }`
    /// or provider-specific error details.
    pub error: Option<JsonValue>,

    /// Backend-scoped runtime control state for streaming and the approval
    /// lifecycle. Intentionally separate from user-facing content
    /// (`turn_messages`).
    ///
    /// Contains:
    /// - `stream_seq`: monotonically increasing counter used as the durable
    ///   boundary between one snapshot and subsequent live SSE events.
    /// - `pending_tool_calls`: tool calls currently waiting for user approval.
    /// - `approval_decisions`: previously recorded approval answers, keyed by
    ///   `pending_call_id`, so approval requests are idempotent.
    ///
    /// Stored as JSONB so the runtime state schema can evolve without DB
    /// migrations. On terminal transitions, `pending_tool_calls` is cleared
    /// while `stream_seq` and recorded decisions remain persisted.
    #[sqlx(json)]
    pub runtime_state: TurnRuntimeState,

    /// When this turn was created (i.e. when the user submitted their input).
    pub created_at: DateTime<Utc>,

    /// When this turn reached a terminal state (`"completed"` or `"failed"`).
    /// `None` while the turn is still in an active lifecycle state.
    /// Used to calculate turn duration and for analytics.
    pub completed_at: Option<DateTime<Utc>>,
}
